# Fastfile

require_relative 'modules/env'
require_relative 'modules/utils'
require_relative 'modules/xcode_setup'

# Defines iOS as default platform
default_platform(:ios)

platform :ios do

  # Prepare environment
  before_all do
    xcodes(version: XcodeSetup.xcode_version)
  end

  # Tests
  lane :test do
    puts "Testing kicked off! 🧪"

    scan(
      devices: Env.test_devices,
      scheme: Env.test_scheme,
      clean: true,
      output_types: "html"
    )
  end

  # Builds
  lane :build do
    build_scheme(scheme: Env.build_scheme)
  end

  # Deploys
  lane :deploy do
    puts "Under construction... 🚜"

    # Deploy to App Center
    # ...
    
    # Deploy to TestFlight
    # upload_to_testflight
  end

  #####
  # Private lanes
  #####

  # Builds
  private_lane :build_scheme do |options|
    scheme = options[:scheme]
    output_name = "HelloWorld_" + scheme

    puts "Building " + scheme + " now... 🍿"

    gym(
      scheme: scheme,
      clean: true,
      output_name: output_name
    )
  end
end

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
