# Fastfile

require_relative 'modules/xcode_setup'
require_relative 'modules/utils'

default_platform(:ios)

platform :ios do

  # Prepare environment
  before_all do
    xcodes(version: XcodeSetup.xcode_version)
  end

  # Tests
  lane :test do
    puts "Testing kicked off! 🧪"

    scan(
      devices: [ENV["SCAN_DEVICE"]],
      scheme: ENV["SCAN_SCHEME"]
    )
  end

  # Builds
  lane :build do
    puts "Building the App now... 🍿"

    gym(
      scheme: ENV["BUILD_SCHEME"],
      clean: true,
      output_name: "HelloWorldApp"
    )
  end

  # Deploys
  lane :deploy do
    puts "Under construction... 🚜"

    # Deploy to App Center
    # ...
    
    # Deploy to TestFlight
    # upload_to_testflight
  end
end

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
