name: "Job: Build"

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      branch_name:
        required: false
        type: string
        default: 'main'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Ruby 2.7.0 and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build the app with Fastlane
        run: fastlane build
        env:
          CI: true
          BUILD_SCHEME: ${{ inputs.scheme }}
