name: Build & Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/actions/build.yml

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/actions/deploy.yml
