name: Build & Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/actions/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/actions/deploy.yml
