name: "Job: Build"

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.7.0
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 2.7.0

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build the app with Fastlane
        run: fastlane build
        env:
          CI: true
          BUILD_SCHEME: inputs.scheme
