name: Build & Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Build
      uses: ./.github/actions/build.yml

  deploy:
    runs-on: macos-latest
    needs: build
    steps:
    - name: Deploy
      uses: ./.github/actions/deploy.yml
