name: "Job: Continuous Delivery"

on:
  workflow_call:
    inputs:
      build_scheme:
        required: true
        type: string
      branch_name:
        required: false
        type: string
        default: 'main'

jobs:
  dev:
    name: Create Dev Build
    uses: ./.github/workflows/ship.yml
    with:
      build_scheme: ${{ inputs.build_scheme }}
      branch_name: ${{ inputs.branch_name }}

  # unprotected:
  #   name: Create Unprotected Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Unprotected'
  #     branch_name: ${{ inputs.branch_name }}

  # live:
  #   name: Create Live Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Live'
  #     branch_name: ${{ inputs.branch_name }}
