name: "Job: Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.7.0
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 2.7.0

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy the app with Fastlane
        run: fastlane deploy
        env:
          CI: true
