name: Main branch: Deploy

on:
  workflow_call:

jobs:
  deploy:
        uses: felipericieri/HelloWorld/.github/workflows/main-build.yml@main
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: gem install fastlane

    - name: Deploy to TestFlight
      run: fastlane deploy
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
