name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: bundler install fastlane

    - name: Install dependencies
      run: bundler exec fastlane install_dependencies

    - name: Run tests
      run: fastlane test

  build:
    needs: test
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: ["HelloWorld", "HelloWorld Sandbox"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: bundler install fastlane

    - name: Build App
      run: fastlane build scheme:${{ matrix.scheme }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-${{ matrix.scheme }}
        path: path/to/your/build/artifacts # Update this path
