name: "Job: Ship (Build & Deploy)"

on:
  workflow_call:
    inputs:
      build_scheme:
        required: true
        type: string
      branch_name:
        required: false
        type: string
        default: 'main'

jobs:
  build:
    name: Builds the app according to scheme
    uses: ./.github/workflows/build.yml
    with:
      scheme: ${{ inputs.build_scheme }}
      branch_name: ${{ inputs.branch_name }}

  deploy:
    needs: build
    name: Deploy to Beta testing
    uses: ./.github/workflows/deploy.yml
