name: "Job: Ship (Build & Deploy)"

on:
  workflow_call:
    inputs:
      build_scheme:
        required: true
        type: string

jobs:
  build:
    name: Builds the app according to scheme
    uses: ./.github/workflows/build.yml
    with:
      scheme: inputs.build_scheme

  deploy:
    needs: build
    name: Deploy to Beta testing
    uses: ./.github/workflows/deploy.yml
