name: "Job: Test"

on:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.6.x
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 2.6.x

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run tests with Fastlane
        run: fastlane test
        env:
          SCAN_DEVICE: 'iPhone 12 Pro'
          SCAN_SCHEME: 'Development' # Replace with your actual scheme
          CI: true
