name: "Workflow: Ship it"

on:
  push:
    branches:
      - main

jobs:
  dev:
    name: Create Dev Build
    uses: ./.github/workflows/ship.yml
    with:
      build_scheme: 'Development'

  # unprotected:
  #   name: Create Unprotected Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Unprotected'

  # live:
  #   name: Create Live Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Live'
