name: "Workflow: Ship it"

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      build_scheme:
        required: true
        type: string
        description: 'Select the scheme you want to use to build the app'
        default: 'Development'

jobs:
  dev:
    name: Create Dev Build
    uses: ./.github/workflows/ship.yml
    with:
      build_scheme: ${{ inputs.build_scheme }}

  # unprotected:
  #   name: Create Unprotected Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Unprotected'

  # live:
  #   name: Create Live Build
  #   uses: ./.github/workflows/ship.yml
  #   with:
  #     build_scheme: 'Live'
